name: shelf_rest_core
description: A concise core for creating monolithic dart API's based on shelf
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.1.1
  shelf_router_generator: ^1.0.1
dependencies:
  jsonable_object: ^1.0.2
  modular_shelf: ^1.0.0
  shelf: ^1.2.0
  shelf_controller_flow_manager: ^1.0.2
  shelf_request_response_2_jsonable_object_utility: ^1.0.1
  shelf_router: ^1.1.1

